USE GerenciadorP_DB;

DROP TABLE TB_AREA;
CREATE TABLE TB_AREA(
COD_AREA INT IDENTITY(1, 1) PRIMARY KEY,
AREA VARCHAR(20));

INSERT INTO TB_AREA(AREA) VALUES('GERENTE');
INSERT INTO TB_AREA(AREA) VALUES('ADMIN');
INSERT INTO TB_AREA(AREA) VALUES('OUTRO');

SELECT * FROM TB_AREA;


DROP TABLE TB_USUARIO;
CREATE TABLE TB_USUARIO(
NOME VARCHAR(40),
EMAIL VARCHAR(40) PRIMARY KEY NOT NULL,
SENHA VARCHAR(20),
AREA INT NOT NULL
FOREIGN KEY(AREA)
REFERENCES TB_AREA(COD_AREA),
PERMISSAO INT NOT NULL);

INSERT INTO TB_USUARIO(NOME,EMAIL,SENHA,AREA,PERMISSAO)
VALUES('FULANO','FULANO@GMAIL.COM','1234',1,0);
INSERT INTO TB_USUARIO(NOME,EMAIL,SENHA,AREA,PERMISSAO)
VALUES('CICLANO','CICLANO@GMAIL.COM','54321',2,0);
INSERT INTO TB_USUARIO(NOME,EMAIL,SENHA,AREA,PERMISSAO)
VALUES('BELTRANO','BELTRANO@GMAIL.COM','9090',3,0);

SELECT * FROM TB_USUARIO;

DROP TABLE TB_EQUIPES;
CREATE TABLE TB_EQUIPES(
COD_EQUIPE INT IDENTITY(1,1) PRIMARY KEY,
FUNCIONARIO VARCHAR(40) NOT NULL
FOREIGN KEY (FUNCIONARIO)
REFERENCES TB_USUARIO(EMAIL),
N_EQUIPE INT NOT NULL);

INSERT INTO TB_EQUIPES(FUNCIONARIO,N_EQUIPE)
VALUES('CICLANO@GMAIL.COM',1);
INSERT INTO TB_EQUIPES(FUNCIONARIO,N_EQUIPE)
VALUES('BELTRANO@GMAIL.COM',1);

SELECT * FROM TB_EQUIPES;

CREATE TABLE TB_PROJETOS(
COD_PROJETO INT IDENTITY(1,1) PRIMARY KEY,
TITULO_PROJ VARCHAR(30) NOT NULL,
DESCRICAO VARCHAR(100),
PRAZO DATE);

INSERT INTO TB_PROJETOS(TITULO_PROJ,PRAZO) -- dd/MM/yyyy || yyyy/MM/dd
VALUES('TESTE2','2021/10/15');

SELECT * FROM TB_PROJETOS

CREATE TABLE TB_STATUS(
COD_STATUS INT PRIMARY KEY NOT NULL,
_STATUS VARCHAR(10) NOT NULL);

INSERT INTO TB_STATUS(COD_STATUS,_STATUS) VALUES(0,'A Fazer');
INSERT INTO TB_STATUS(COD_STATUS,_STATUS) VALUES(1,'Fazendo');
INSERT INTO TB_STATUS(COD_STATUS,_STATUS) VALUES(2,'Concluído');

SELECT * FROM TB_STATUS;


DROP TABLE TB_TAREFAS;
CREATE TABLE TB_TAREFAS(
COD_TAREFA INT IDENTITY(1,1) PRIMARY KEY,
DESCRICAO VARCHAR(100),
STATUS_TAREFA INT
FOREIGN KEY (STATUS_TAREFA)
REFERENCES TB_STATUS(COD_STATUS),
PROJETO INT
FOREIGN KEY (PROJETO)
REFERENCES TB_PROJETOS(COD_PROJETO),
EQUIPE INT
FOREIGN KEY (EQUIPE)
REFERENCES TB_EQUIPES(COD_EQUIPE));

INSERT INTO TB_TAREFAS(DESCRICAO,STATUS_TAREFA,PROJETO,EQUIPE) VALUES('FAZER O BD',0,1,1);
INSERT INTO TB_TAREFAS(DESCRICAO,STATUS_TAREFA,PROJETO,EQUIPE) VALUES('CONVERSAR SOBRE O PROJETO',2,1,1);

SELECT * FROM TB_TAREFAS;

UPDATE TB_TAREFAS SET STATUS_TAREFA=1 WHERE COD_TAREFA=1;

SELECT * FROM TB_TAREFAS WHERE STATUS_TAREFA=1;
SELECT * FROM TB_TAREFAS WHERE STATUS_TAREFA=2;